name: adventofcode_2025
description: Advent of Code 2025 solutions.
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  path: ^1.9.0
  prompts: ^2.0.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.25.6
